import "./globals.css";
import CustomSessionProvider from './providers/SessionProvider'; // Importer le CustomSessionProvider

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CustomSessionProvider>{children}</CustomSessionProvider> {/* Envelopper les enfants avec CustomSessionProvider */}
      </body>
    </html>
  );
}
